# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-09 09:12:14
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: "${{ github.run_number }} [${{ github.actor }}] ${{ github.head_ref }} -> ${{ github.base_ref }}"

on:
  pull_request:
    branches:
      - main

jobs:
  _ea6be881-f2ed-45dd-8258-45ac0cbe006e:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_VSCodeMixin/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch: ${{ github.head_ref }}

  _dcb3b81f-ec28-4812-a6f9-b29e69725ab8:
    name: "Validate Pull Request (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate_pull_request.yaml@CI-latest
    with:
      job_name_prefix: Common_VSCodeMixin
      is_mixin_repository: true
      repo_name: davidbrownell/v4-Common_VSCodeMixin
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: None
