# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-09 09:12:06
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

concurrency: "on_push-${{ github.ref_name }}"

jobs:
  _082e5b93-277a-4908-8db6-8a9c0abff1f6:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_VSCodeMixin/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

  _164c9d32-7f71-478d-8204-a9a04dbf07ca:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _082e5b93-277a-4908-8db6-8a9c0abff1f6
